name: flutter_network_utils
description: "Flutter dio network utils"
version: 0.0.3
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.5.0+1
  path_provider: any

  flutter_commons:
    git:
      url: "https://github.com/Anfet/flutter_commons.git"
      ref: "release/1.0.15"


dev_dependencies:
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: SpaceMono
      fonts:
        - asset: lib/fonts/SpaceMono-Regular.ttf
  assets:
    - lib/fonts/
